# tasks file for wordpress
- hosts: aws
  become: true
  gather_facts: false
  vars_files:
     - wp_vars.yml

  tasks:

   - name: Installing Softwares
     apt:
         name: "{{ item }}"
         state: present
     loop:
         - php
         - php-mysql

   - name:  Starting the services   
     service:
         name: "{{ item }}"
         state: started
         enabled: true
     loop:
         - apache2
         - mysql
         
   - name: Download WordPress
     get_url:
         url=https://wordpress.org/latest.tar.gz
         dest=/tmp/wordpress.tar.gz
         validate_certs=no

   - name: Extract WordPress
     unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

   - name: Update default Apache site
     copy:
      src: /templates/wp_vhosts.conf
      dest: /etc/apache2/sites-enabled/000-default.conf
     notify:
       - restart apache

   - name: Copy sample config file
     command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

# Create database
   - name: Create a new database with name 'wpdb'
     mysql_db:
       name: wpdb
       state: present
     become: true
  
 # Create database user with name 'wpdb_user' and password '12345' with all database privileges
   - name: Create a new user with name 'wpdb_user'
     mysql_user:
       name: wpdb_user
       password: 12345
       priv: '*.*:ALL,GRANT'
       state: present

   - name: Creating WordPress config file
     template:
         src: /templates/wp-config.php.j2
         dest: /var/www/wordpress/wp-config.php   

   - name: Setting WordPress permissions
     shell: "{{ item }}"
     with_items:
         - 'find . -type d -exec chmod 755 {} \;'
         - 'find . -type f -exec chmod 644 {} \;'       

